<a href="https://colab.research.google.com/github/Hellokrrish/Machine-Learning/blob/main/KNN(Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=3,noise=2,random_state=1)

In [5]:
x

array([[ 1.45167891,  0.3416886 , -0.12517266],
       [-0.7003985 , -0.20339445,  0.24266944],
       [-0.10646012, -2.79099641, -0.45611756],
       ...,
       [-0.56282904, -1.2514994 ,  1.29857162],
       [-1.16896134, -1.8994631 , -2.5399554 ],
       [ 0.88608992,  0.31897183,  0.26486763]])

In [6]:
y

array([ 1.41260371e+02, -5.67041943e+01, -2.98321752e+02,  7.20343998e+01,
        4.99631562e+01,  1.56582433e+02,  2.03051403e+02,  2.58776781e+01,
       -4.40659143e+02, -1.70439127e+02,  5.18398395e+01,  2.08017433e+02,
       -9.36682880e+01,  9.34260305e+01, -2.96803257e+02,  7.60019972e+01,
       -1.45861782e+02,  1.14985854e+02,  1.24093100e+02, -1.40657385e+02,
       -1.77583278e+02,  1.22323006e+02, -1.77852767e+01, -8.13756593e+01,
       -7.04298996e+01, -1.53194402e+02,  1.92218738e+02,  2.22520963e+01,
       -8.09848828e+01, -9.75767292e+01,  1.54798231e+02, -7.82947705e+01,
       -8.37967988e+01,  7.98693775e+01,  2.36435514e+02, -2.38021706e+02,
        2.98816714e+02, -4.68211059e+01,  2.49296463e+02,  1.73766759e+02,
        2.98697697e-02, -2.99265969e+02, -2.62549752e+02,  1.74379768e+01,
        1.46953645e+02, -5.52345221e+01, -1.19531105e+01,  3.53446268e+02,
       -7.92940463e+01,  3.42013902e+01, -1.95887981e+01,  1.79051357e+02,
        6.82572683e+01,  

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [8]:
x_train.shape,x_test.shape

((700, 3), (300, 3))

In [10]:
from sklearn.neighbors import KNeighborsRegressor
clf=KNeighborsRegressor()
clf.fit(x_train,y_train)

KNeighborsRegressor()

In [11]:
y_pred=clf.predict(x_test)

In [12]:
y_pred

array([ -54.26135027,  -16.49852978, -101.98111243,    3.83239425,
         -3.4261038 ,    2.76080235,  272.32711802,  -53.05208068,
        130.13928807,    8.60020639, -180.82101701,   -4.15811129,
        147.88608863,    8.14003894, -154.51310702,   56.918506  ,
       -188.3039359 ,  191.49436359,  -41.85138175,   23.65532483,
        152.88195302,  119.1529257 , -108.3771699 ,  -38.0458122 ,
        -28.75836406,  326.46354427,  180.10168248,   31.89047778,
         13.43434132,   80.3550571 ,  -80.40397713,   -9.24632571,
        -64.55943245,  273.5515883 ,  -21.34262512, -194.33691679,
        141.70447014,  205.84055431,  -11.66927795,  170.63976419,
          4.13966959,  165.17182578,   34.40006362, -216.54515584,
       -219.36115558,  -10.86154654, -211.07265381, -264.67966394,
       -114.21820987,  147.07038072, -219.1159513 ,  232.48949871,
         -4.35618153, -190.68049855,  222.9246909 ,  114.49508886,
         11.61133484,  -59.63113852,  144.60424284, -114.36169

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9690989198771399

In [15]:
param_grid={'n_neighbors':[3,5,6,7,10,12,15],
            'algorithm':['ball_tree', 'kd_tree', 'brute'],
            'leaf_size':[10,15,20,25,30,35,40],
            }

In [16]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=clf,param_grid=param_grid,cv=5,verbose=4)

In [17]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 147 candidates, totalling 735 fits
[CV 1/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=3;, score=0.969 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=3;, score=0.971 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=3;, score=0.967 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=3;, score=0.979 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=3;, score=0.958 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=5;, score=0.973 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=5;, score=0.969 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=5;, score=0.967 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=5;, score=0.973 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=10, n_neighbors=5;, score=0.945 total 

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 40],
                         'n_neighbors': [3, 5, 6, 7, 10, 12, 15]},
             verbose=4)

In [18]:
grid.best_params_

{'algorithm': 'ball_tree', 'leaf_size': 10, 'n_neighbors': 3}

In [19]:
best_model=grid.best_estimator_
y_pred=best_model.predict(x_test)

In [21]:
r2_score(y_test,y_pred)

0.9737908382904431